### PR TITLE
[7581] add user reports to moderation comment serializer

### PR DESCRIPTION
**Pull request by hklarner**
- this PR depends on a PR on adhocracy4
    - https://github.com/liqd/adhocracy4/pull/1477

### CODE REVIEW

**Review by goapunk — CHANGES_REQUESTED** [review]
looks good to me, needs changelog and a test (at least add the `user_reports` field to the `test_fields()` I'd say)

**Comment by hklarner** [comment]
@goapunk no idea why I cannot reply + resolve your comment. Seems to be different for "review requested" than for "create comment". Anyways, I added a commit for your changes:
- https://github.com/liqd/a4-defakts/pull/18/commits/d8ec376e8e90372eea6b631577acf83b09ae8473

**Review by m4ra — COMMENTED** [review]
the names of the response data (`received_data[n]` where n is 0 to 2) in the tests are a bit diff to get in the assertions for which comments correspond.

**Review by goapunk — APPROVED** [review]
lgtm, only thing to maybe fix is the readability of the test

**Comment by hklarner** [comment]
@goapunk @MariaLiquid made changes to the readability of the test (renamed lists to `comments_created` and `comments_received` as discussed with @MariaLiquid), see
- 5ff8036bcfc566e8c5272c9d49cd244b71d09a3a

**Review by m4ra — APPROVED** [review]

**Comment by hklarner** [comment]
@goapunk @m4ra I will do a final rebase and add the review changes to the fitting commits once you approve. I can also do this every time I make changes - if you want - but I think it is easier for you to see the latest changes this way.

**Comment by m4ra** [comment]
> @goapunk @m4ra I will do a final rebase and add the review changes to the fitting commits once you approve. I can also do this every time I make changes - if you want - but I think it is easier for you to see the latest changes this way.

rebase happens automatically when we merge if there are no conflicts with the main branch.

**Comment by hklarner** [comment]
> rebase happens automatically when we merge if there are no conflicts with the main branch.

I meant getting rid of the two commits "pull request review changes".

**Pull request merged**
